# Generated by Django 5.2.8 on 2026-01-28 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_propagatedeffectbyln_unique_prop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubroutineElmtypesByConfig',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(max_length=2)),
                ('ln', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_instances_by_config', to='app.usertypeinstances')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_members_by_config', to='app.typedefinitions')),
                ('subroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subroutine_dtype_vars_by_config', to='app.subroutines')),
            ],
            options={
                'db_table': 'elmtype_access_for_config',
                'indexes': [models.Index(fields=['config_hash', 'subroutine'], name='elmtype_acc_config__ce32c1_idx'), models.Index(fields=['last_used_at'], name='elmtype_acc_last_us_e44b57_idx')],
            },
        ),
    ]
