from ..models import (
    ArgAccess,
    CallsiteBinding,
    CascadeDependence,
    CascadePair,
    ConfigProfile,
    FlatIf,
    FlatIFCascadeVar,
    FlatIfNamelistVar,
    IntrinsicGlobals,
    ModuleDependency,
    Modules,
    NamelistVariable,
    PresetConfig,
    SubroutineActiveGlobalVars,
    SubroutineArgs,
    SubroutineCalltree,
    SubroutineIntrinsicGlobals,
    SubroutineLocalArrays,
    Subroutines,
    TypeDefinitions,
    UserTypes,
    UserTypeInstances,
)

VIEWS_TABLE_DICT = {
    "subroutines": {
        "name": Subroutines,
        "html": "subroutines.html",
        "fields": {
            "Id": "subroutine_id",
            "Module": "module.module_name",
            "Subroutine": "subroutine_name",
        },
        "title": "Table of Subroutines",
    },
    "modules": {
        "name": Modules,
        "html": "modules.html",
        "fields": {
            "Id": "module_id",
            "Module": "module_name",
        },
        "title": "Table of Modules",
    },
    "subroutine_calltree": {
        "name": SubroutineCalltree,
        "html": "subroutine_calltree.html",
        "fields": {
            "Id": "parent_id",
            "Parent Sub": "parent_subroutine.subroutine_name",
            "Child Sub": "child_subroutine.subroutine_name",
            "Lineno": "lineno",
        },
        "title": "Table of Subroutine Call Tree",
    },
    "types": {
        "name": TypeDefinitions,
        "html": "types.html",
        "fields": {
            "Id": "define_id",
            "Module": "type_module.module_name",
            "Type Name": "user_type.user_type_name",
            "Member Type": "member_type",
            "Member Name": "member_name",
            "Dim": "dim",
            "Bounds": "bounds",
        },
        "title": "Table of Type Definitions",
    },
    "dependency": {
        "name": ModuleDependency,
        "html": "dep.html",
        "fields": {
            "Id": "dependency_id",
            "Module": "module.module_name",
            "Dependent Mod": "dep_module.module_name",
            "Used object": "object_used",
        },
        "title": "Table of Module Dependencies",
    },
    "instances": {
        "name": UserTypeInstances,
        "html": "instances.html",
        "fields": {
            "Id": "instance_id",
            "Module": "instance_type.module.module_name",
            "Type Name": "instance_type.user_type_name",
            "Instance Name": "instance_name",
        },
        "title": "Table of User Type Instances",
    },
    "subroutineargs": {
        "name": SubroutineArgs,
        "html": "subroutineargs.html",
        "fields": {
            "Id": "arg_id",
            "Subroutine": "subroutine.subroutine_name",
            "Arg Type": "arg_type",
            "Arg Name": "arg_name",
            "Dim": "dim",
        },
        "title": "Table of Subroutine Arguments",
    },
    "activeglobalvars": {
        "name": SubroutineActiveGlobalVars,
        "html": "active_global_vars.html",
        "fields": {
            "Id": "variable_id",
            "Subroutine": "subroutine.subroutine_name",
            "Inst": "instance.instance_name",
            "Member": "member.member_name",
            "Status": "status",
            "ln": "ln",
        },
        "title": "Table of Global Vars by Subroutine",
    },
    "intrinsicglobalvars": {
        "name": IntrinsicGlobals,
        "html": "intrinsic_gvs.html",
        "fields": {
            "Id": "var_id",
            "Module": "gv_module.module",
            "Type": "var_type",
            "Name": "var_name",
            "Dim": "dim",
            "Bounds": "bounds",
            "Default": "value",
        },
        "title": "Table of Intrinsic type Globals",
    },
    "subroutineintrinsicglobals": {
        "name": SubroutineIntrinsicGlobals,
        "html": "active_intrinsics.html",
        "fields": {
            "Id": "sub_gv_id",
            "Module": "sub_id.module.module_name",
            "Subroutine": "sub_id.subroutine_name",
            "Type": "gv_id.var_type",
            "Name": "gv_id.var_name",
        },
        "title": "Table of Active Intrinsic Globals",
    },
    "namelistvars": {
        "name": NamelistVariable,
        "html": "namelist",
        "fields": {
            "Id": "nml_id",
            "Module": "active_var_id.gv_module.module_name",
            "Type": "active_var_id.var_type",
            "Name": "active_var_id.var_name",
            "Dim": "active_var_id.dim",
            "Bounds": "active_var_id.bounds",
            "Default": "active_var_id.value",
        },
        "title": "Table of Namelist Variables",
    },
    "flat_ifs": {
        "name": FlatIf,
        "html": "flat_ifs",
        "fields": {
            "Id": "flatif_id",
            "Module": "subroutine.module.module_name",
            "Subroutine": "subroutine.subroutine_name",
            "Start": "start_ln",
            "End": "end_ln",
            "Cond.": "condition",
        },
        "title": "Table of If Blocks",
    },
    "if_nml": {
        "name": FlatIfNamelistVar,
        "html": "if_nml",
        "fields": {
            "Id": "id",
            "Module": "flatif.subroutine.module.module_name",
            "Subroutine": "flatif.subroutine.subroutine_name",
            "Start": "flatif.start_ln",
            "End": "flatif.end_ln",
            "Name": "namelist_var.active_var_id.var_name",
            "Default": "namelist_var.active_var_id.value",
            "Cond.": "flatif.condition",
        },
        "title": "Table of Ifs with NML Conditions",
    },
    "arg_access": {
        "name": ArgAccess,
        "html": "arg_access",
        "fields": {
            "Subroutine": "subroutine.subroutine_name",
            "Arg": "arg.arg_name",
            "Member": "member_path",
            "ln": "ln",
            "status": "status",
        },
        "title": "Table of Arg Access by Ln",
    },
    "cascades":{
        "name" : CascadePair,
        "html":"cascades",
        "fields":{
            "Namelist" : "dependence.trigger_var.active_var_id.var_name",
            "Cascade Var":"dependence.cascade_var",
            "NML Value" : "nml_val",
            "Cascade Val" : "cascade_val",
        },
        "title" : "Table of Cascade Relations",
    },
    "ifs_cascade": {
        "name": FlatIFCascadeVar,
        "html": "ifs_cascade",
        "fields": {
            "Id": "cv_if_id",
            "Module": "flatif_cv.subroutine.module.module_name",
            "Subroutine": "flatif_cv.subroutine.subroutine_name",
            "Start": "flatif_cv.start_ln",
            "End": "flatif_cv.end_ln",
            "Var": "cascade.cascade_var",
            "Cond.": "flatif_cv.condition",
        },
        "title": "Table of Ifs with Cascade Conditions",
    },
}
