# Generated by Django 5.2.8 on 2026-01-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_subroutineelmtypesbyconfig_arg_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='callsitebinding',
            name='uniq_binding_per_arg',
        ),
        migrations.AddConstraint(
            model_name='callsitebinding',
            constraint=models.UniqueConstraint(fields=('parent_subroutine', 'call', 'dummy_arg', 'var_name', 'member_path_str', 'nested_level'), name='uniq_binding_per_arg'),
        ),
    ]
