"""
Functions to "integrate back" developer edits made inside a SPEL unit-test
case directory into the real E3SM source tree.

During unit-test generation (see `spel.scripts.edit_files`), dependencies that
aren't needed for the functional unit test are commented out of the copied
source files using a `!#py ` token prefix so that they can later be restored
with a simple search-and-replace. This module finds files within a unit-test
case that a developer has actually modified (as opposed to files SPEL simply
generated/copied when the case was created), strips the `!#py ` token back
out, and copies the result back to its original location under
`E3SM_SRCROOT`.

Files that originate from `SPEL/SourceFiles/` (netCDF-interface, decomposition
and driver stubs written specifically for the unit-test harness) are never
copied back -- they have no corresponding "real" counterpart in E3SM and
blindly restoring them would corrupt the source tree.
"""

from __future__ import annotations

import json
import re
import subprocess as sp
from collections import Counter
from logging import Logger
from pathlib import Path
from typing import Optional

from spel.scripts.config import (
    CASE_META_FILENAME,
    E3SM_SRCROOT,
    spel_mods_dir,
    unittests_dir,
)
from spel.scripts.fortran_modules import get_module_name_from_file
from spel.scripts.logging_configs import get_logger

COMMENT_TOKEN = "!#py "
_TOKEN_RE = re.compile(rf"^(\s*){re.escape(COMMENT_TOKEN)}")

# `insert_header_for_unittest` (fortran_modules.py) inserts this raw include
# line (not wrapped in COMMENT_TOKEN) right after the `module` statement of
# every file used in a unit test, to pull in unit-test-only overrides. It
# must never be copied back into the real source tree.
_UNITTEST_HEADER_RE = re.compile(r'^\s*#include\s+"unittest_defs\.h"\s*\n?$')

# Files generated by SPEL itself that have a same-named module somewhere in
# the real E3SM source tree, but whose unit-test content is a stub/generated
# replacement rather than a trimmed copy of the real file. These must never
# be copied back even though `get_filename_from_module` can resolve a
# destination for them.
GENERATED_ONLY_FILES = {
    "elm_instMod.F90",
    "duplicateMod.F90",
}


def read_case_srcroot(case_dir: Path, logger: Logger) -> Path:
    """
    Read the E3SM_SRCROOT that `spel create` recorded for this case in
    `CASE_META_FILENAME` (see `FunctionalUnitTest.write_meta_file`).

    Falls back to the currently configured `E3SM_SRCROOT` (with a warning)
    for cases generated before this metadata file existed.
    """
    meta_path = case_dir / CASE_META_FILENAME
    if not meta_path.is_file():
        logger.warning(
            f"{meta_path} not found -- falling back to the currently "
            f"configured E3SM_SRCROOT ({E3SM_SRCROOT}). Re-run 'spel create' "
            "for this case to record its source root."
        )
        return E3SM_SRCROOT

    try:
        meta = json.loads(meta_path.read_text())
        srcroot = Path(meta["e3sm_srcroot"]).expanduser().resolve()
    except (KeyError, ValueError, OSError) as e:
        logger.warning(
            f"Could not read E3SM_SRCROOT from {meta_path} ({e}) -- falling "
            f"back to the currently configured E3SM_SRCROOT ({E3SM_SRCROOT})"
        )
        return E3SM_SRCROOT

    if srcroot != E3SM_SRCROOT.resolve():
        logger.info(
            f"Case '{case_dir.name}' was generated against {srcroot}, which "
            f"differs from the currently configured E3SM_SRCROOT "
            f"({E3SM_SRCROOT}) -- restoring using the case's recorded root."
        )
    return srcroot


def _resolve_module_filepath(
    module_name: str, elm_src: Path, shr_src: Path
) -> Optional[str]:
    """
    Given a module name, find its file path under `elm_src` (falling back to
    `shr_src`). Mirrors `fortran_modules.get_filename_from_module`, but is
    parameterized by source root instead of relying on the module-level
    ELM_SRC/SHR_SRC globals, since a case may have been generated against a
    different E3SM_SRCROOT than the one currently configured.
    """
    cmd = (
        rf'grep -rin --exclude-dir=external_models/ '
        rf'"^\s*module\s* {module_name}" {elm_src}*'
    )
    output = sp.getoutput(cmd)
    if not output:
        cmd = (
            f'grep -rin --exclude-dir=external_models/ '
            f'"module {module_name}" {shr_src}*'
        )
        output = sp.getoutput(cmd)
        if not output:
            return None

    file_path = output.split("\n")[0].split(":")[0]
    if file_path.split(".")[-1].lower() != "f90":
        return None
    return file_path


def source_files_exclude_set() -> set[str]:
    """
    Basenames of files that are copied verbatim from SPEL/SourceFiles/ (or are
    otherwise purely SPEL-generated) when a unit-test case is created. These
    should never be copied back into the E3SM source tree.
    """
    exclude = {p.name for p in spel_mods_dir.glob("*") if p.is_file()}
    exclude.update(GENERATED_ONLY_FILES)
    return exclude


def find_changed_files(case_dir: Path, exclude_names: set[str]) -> list[Path]:
    """
    Identify files in `case_dir` that were modified by a developer after the
    unit test was generated.

    All files are written/copied in a tight batch when `spel create` builds a
    case, so the vast majority share one common mtime (to the nearest
    second). Files touched afterwards by a developer end up with a distinct
    mtime. We take the most common mtime as the "creation" baseline and treat
    any `.F90` file with a different mtime as changed.
    """
    all_files = sorted(p for p in case_dir.glob("*.F90") if p.is_file())
    if not all_files:
        return []

    mtimes = {p: int(p.stat().st_mtime) for p in all_files}
    baseline, _ = Counter(mtimes.values()).most_common(1)[0]

    changed = [
        p
        for p in all_files
        if mtimes[p] != baseline and p.name not in exclude_names
    ]
    return changed


def remove_comment_token(text: str) -> str:
    """
    Strip the leading `!#py ` restoration token from every line, and drop
    the unit-test-only `#include "unittest_defs.h"` header line that
    `insert_header_for_unittest` adds to every file in a case.
    """
    lines = text.splitlines(keepends=True)
    lines = [line for line in lines if not _UNITTEST_HEADER_RE.match(line)]
    return "".join(_TOKEN_RE.sub(r"\1", line) for line in lines)


def restore_case(
    casename: str,
    dry_run: bool = False,
    yes: bool = False,
    logger: Logger = None,
) -> list[Path]:
    """
    Find files changed in the unit-test case `casename`, strip the `!#py `
    restoration token, and copy them back to their original location in
    E3SM_SRCROOT.

    Returns the list of destination paths that were (or would be, in
    dry-run mode) written.
    """
    logger = logger or get_logger("restore_files")

    case_dir = unittests_dir / casename
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Unit-test case not found: {case_dir}")

    case_srcroot = read_case_srcroot(case_dir, logger)
    elm_src = case_srcroot / "components/elm/src/"
    shr_src = case_srcroot / "share/util/"

    exclude_names = source_files_exclude_set()
    changed_files = find_changed_files(case_dir, exclude_names)

    if not changed_files:
        logger.info(f"No modified files found in unit-test case '{casename}'")
        return []

    # Resolve destination paths, skipping anything we can't safely map back.
    plan: list[tuple[Path, Path]] = []
    for src in changed_files:
        try:
            _, module_name = get_module_name_from_file(str(src))
        except Exception:
            logger.warning(f"Could not determine module name for {src.name} -- skipping")
            continue

        dest_str = _resolve_module_filepath(module_name, elm_src, shr_src)
        if dest_str is None:
            logger.warning(
                f"Could not resolve a destination in {case_srcroot} for "
                f"module '{module_name}' ({src.name}) -- skipping"
            )
            continue

        dest = Path(dest_str).resolve()
        if case_srcroot.resolve() not in dest.parents:
            logger.warning(
                f"Resolved destination {dest} for {src.name} is outside "
                f"{case_srcroot} -- skipping"
            )
            continue

        plan.append((src, dest))

    if not plan:
        logger.info("Nothing to restore -- all changed files were excluded")
        return []

    logger.info(f"Files to restore for case '{casename}':")
    for src, dest in plan:
        logger.info(f"  {src.name}  ->  {dest}")

    if dry_run:
        return [dest for _, dest in plan]

    if not yes:
        answer = input(f"Copy {len(plan)} file(s) back into {case_srcroot}? [y/N] ")
        if answer.strip().lower() not in ("y", "yes"):
            logger.info("Aborted -- no files were copied")
            return []

    restored: list[Path] = []
    for src, dest in plan:
        restored_text = remove_comment_token(src.read_text())
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(restored_text)
        restored.append(dest)
        logger.info(f"Restored {src.name} -> {dest}")

    return restored
