# Generated by Django 5.2.8 on 2026-01-14 05:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatIf',
            fields=[
                ('flatif_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_ln', models.IntegerField()),
                ('end_ln', models.IntegerField()),
                ('condition', models.JSONField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'flat_if_blocks',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='SubroutineArgs',
            fields=[
                ('arg_id', models.AutoField(primary_key=True, serialize=False)),
                ('arg_type', models.CharField(max_length=100)),
                ('arg_name', models.CharField(max_length=100)),
                ('dim', models.IntegerField()),
            ],
            options={
                'db_table': 'subroutine_args',
            },
        ),
        migrations.CreateModel(
            name='SubroutineCalltree',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('args', models.TextField(default='')),
                ('lineno', models.IntegerField()),
            ],
            options={
                'db_table': 'subroutine_calltree',
            },
        ),
        migrations.CreateModel(
            name='IntrinsicGlobals',
            fields=[
                ('var_id', models.AutoField(primary_key=True, serialize=False)),
                ('dim', models.IntegerField()),
                ('var_type', models.CharField(max_length=50)),
                ('var_name', models.CharField(max_length=100)),
                ('bounds', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('gv_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_var', to='app.modules')),
            ],
            options={
                'db_table': 'intrinsic_globals',
            },
        ),
        migrations.CreateModel(
            name='NamelistVariable',
            fields=[
                ('nml_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_var_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namelist', to='app.intrinsicglobals')),
            ],
            options={
                'db_table': 'namelist_variables',
            },
        ),
        migrations.CreateModel(
            name='FlatIfNamelistVar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flatif')),
                ('namelist_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namelistvariable')),
            ],
            options={
                'db_table': 'flat_if_namelist',
            },
        ),
        migrations.CreateModel(
            name='CascadeDependence',
            fields=[
                ('cascade_id', models.AutoField(primary_key=True, serialize=False)),
                ('cascade_var', models.CharField(max_length=100)),
                ('trigger_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='app.namelistvariable')),
            ],
        ),
        migrations.CreateModel(
            name='PresetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('preset_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'preset_configs',
                'indexes': [models.Index(fields=['preset_hash'], name='preset_conf_preset__03b97b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallsiteBinding',
            fields=[
                ('binding_id', models.AutoField(primary_key=True, serialize=False)),
                ('nested_level', models.IntegerField()),
                ('scope', models.CharField(max_length=32)),
                ('var_name', models.CharField(max_length=255)),
                ('member_path_str', models.CharField(db_index=True, default='', max_length=255)),
                ('dummy_arg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutineargs')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='app.subroutinecalltree')),
            ],
            options={
                'db_table': 'callsite_binding',
            },
        ),
        migrations.CreateModel(
            name='PropagatedEffectByLn',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('var_name', models.CharField(max_length=255)),
                ('member_path', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=2)),
                ('lineno', models.IntegerField()),
                ('scope', models.CharField(max_length=32)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagated_effects', to='app.callsitebinding')),
                ('call_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagated_call_site', to='app.subroutinecalltree')),
            ],
            options={
                'db_table': 'propagated_access_by_ln',
            },
        ),
        migrations.CreateModel(
            name='Subroutines',
            fields=[
                ('subroutine_id', models.AutoField(primary_key=True, serialize=False)),
                ('subroutine_name', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subroutine_module', to='app.modules')),
            ],
            options={
                'db_table': 'subroutines',
            },
        ),
        migrations.CreateModel(
            name='SubroutineLocalArrays',
            fields=[
                ('local_arry_id', models.AutoField(primary_key=True, serialize=False)),
                ('array_name', models.CharField(max_length=100)),
                ('dim', models.IntegerField()),
                ('subroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subroutine_locals', to='app.subroutines')),
            ],
            options={
                'db_table': 'subroutine_local_arrays',
            },
        ),
        migrations.CreateModel(
            name='SubroutineIntrinsicGlobals',
            fields=[
                ('sub_gv_id', models.AutoField(primary_key=True, serialize=False)),
                ('gv_ln', models.IntegerField(default=-1)),
                ('gv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_intrinsic', to='app.intrinsicglobals')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subroutine_global_vars', to='app.subroutines')),
            ],
            options={
                'db_table': 'subroutine_intrinsic_globals',
            },
        ),
        migrations.AddField(
            model_name='subroutinecalltree',
            name='child_subroutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_subroutine', to='app.subroutines'),
        ),
        migrations.AddField(
            model_name='subroutinecalltree',
            name='parent_subroutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_subroutine', to='app.subroutines'),
        ),
        migrations.AddField(
            model_name='subroutineargs',
            name='subroutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subroutine_args', to='app.subroutines'),
        ),
        migrations.CreateModel(
            name='IfEvaluationByHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('start_ln', models.IntegerField()),
                ('end_ln', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('flatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flatif')),
                ('subroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutines')),
            ],
            options={
                'db_table': 'if_eval_by_hash',
            },
        ),
        migrations.AddField(
            model_name='flatif',
            name='subroutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_ifs', to='app.subroutines'),
        ),
        migrations.CreateModel(
            name='CallsitePropagatedEffectByHash',
            fields=[
                ('effect_id', models.AutoField(primary_key=True, serialize=False)),
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('var_name', models.CharField(db_index=True, max_length=255)),
                ('member_path_str', models.CharField(db_index=True, default='', max_length=255)),
                ('kind', models.CharField(max_length=32)),
                ('child_ln', models.IntegerField()),
                ('status', models.CharField(max_length=2)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutinecalltree')),
                ('child_subroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutines')),
            ],
            options={
                'db_table': 'callsite_propagated_effect',
            },
        ),
        migrations.AddField(
            model_name='callsitebinding',
            name='parent_subroutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_binding_parent', to='app.subroutines'),
        ),
        migrations.CreateModel(
            name='ArgSummaryByHash',
            fields=[
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('arg_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('ln', models.IntegerField()),
                ('status', models.CharField(max_length=2)),
                ('member_path', models.CharField(max_length=255)),
                ('arg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutineargs')),
                ('subroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutines')),
            ],
            options={
                'db_table': 'arg_access_by_hash',
            },
        ),
        migrations.CreateModel(
            name='ArgAccess',
            fields=[
                ('arg_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('ln', models.IntegerField()),
                ('status', models.CharField(max_length=2)),
                ('member_path', models.CharField(max_length=255)),
                ('arg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutineargs')),
                ('subroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subroutines')),
            ],
            options={
                'db_table': 'arg_access',
            },
        ),
        migrations.CreateModel(
            name='TypeDefinitions',
            fields=[
                ('define_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_type', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('dim', models.IntegerField()),
                ('bounds', models.CharField(max_length=100)),
                ('type_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_def_module', to='app.modules')),
            ],
            options={
                'db_table': 'type_definitions',
            },
        ),
        migrations.CreateModel(
            name='UserTypeInstances',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=100)),
                ('inst_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_module', to='app.modules')),
            ],
            options={
                'db_table': 'user_type_instances',
            },
        ),
        migrations.CreateModel(
            name='SubroutineActiveGlobalVars',
            fields=[
                ('variable_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=2)),
                ('ln', models.IntegerField(default=-1)),
                ('subroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subroutine_dtype_vars', to='app.subroutines')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_member', to='app.typedefinitions')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_instances', to='app.usertypeinstances')),
            ],
            options={
                'db_table': 'subroutine_active_global_vars',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=100, unique=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type_module', to='app.modules')),
            ],
            options={
                'db_table': 'user_types',
            },
        ),
        migrations.AddField(
            model_name='usertypeinstances',
            name='instance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_type', to='app.usertypes'),
        ),
        migrations.AddField(
            model_name='typedefinitions',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type_def', to='app.usertypes'),
        ),
        migrations.CreateModel(
            name='CascadePair',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('nml_val', models.CharField(max_length=64)),
                ('cascade_val', models.CharField(max_length=64)),
                ('dependence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='app.cascadedependence')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dependence', 'nml_val', 'cascade_val'), name='unique_pair')],
            },
        ),
        migrations.CreateModel(
            name='ConfigProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('user_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_profile',
                'indexes': [models.Index(fields=['owner', 'user_hash'], name='config_prof_owner_i_bbe804_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='uniq_configprofile_name_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='FlatIFCascadeVar',
            fields=[
                ('cv_if_id', models.AutoField(primary_key=True, serialize=False)),
                ('cascade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cascadedependence')),
                ('flatif_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flatif')),
            ],
            options={
                'db_table': 'flat_if_cascade',
                'constraints': [models.UniqueConstraint(fields=('flatif_cv', 'cascade'), name='uniq_flatif_cascade')],
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('dependency_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_used', models.CharField(max_length=100)),
                ('dep_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduledependency_dep_module_set', to='app.modules')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modules')),
            ],
            options={
                'db_table': 'module_dependency',
                'constraints': [models.UniqueConstraint(fields=('module', 'dep_module', 'object_used'), name='unique_mod_dep')],
            },
        ),
        migrations.AddIndex(
            model_name='intrinsicglobals',
            index=models.Index(fields=['gv_module', 'var_name'], name='intrinsic_g_gv_modu_4132ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='intrinsicglobals',
            constraint=models.UniqueConstraint(fields=('gv_module', 'var_name'), name='unique_globals'),
        ),
        migrations.AddConstraint(
            model_name='namelistvariable',
            constraint=models.UniqueConstraint(fields=('active_var_id',), name='unique_nml_var'),
        ),
        migrations.AddConstraint(
            model_name='flatifnamelistvar',
            constraint=models.UniqueConstraint(fields=('flatif', 'namelist_var'), name='unique_flatif_var'),
        ),
        migrations.AddConstraint(
            model_name='cascadedependence',
            constraint=models.UniqueConstraint(fields=('cascade_var', 'trigger_var'), name='unique_dependence'),
        ),
        migrations.AddConstraint(
            model_name='propagatedeffectbyln',
            constraint=models.UniqueConstraint(fields=('binding', 'var_name', 'lineno', 'status', 'member_path'), name='unique_prop'),
        ),
        migrations.AddConstraint(
            model_name='subroutines',
            constraint=models.UniqueConstraint(fields=('subroutine_name', 'module'), name='unique_subs'),
        ),
        migrations.AddConstraint(
            model_name='subroutinelocalarrays',
            constraint=models.UniqueConstraint(fields=('subroutine', 'array_name'), name='unique_sub_locals'),
        ),
        migrations.AddConstraint(
            model_name='subroutineintrinsicglobals',
            constraint=models.UniqueConstraint(fields=('gv_id', 'sub_id'), name='unique_sub_intrinsic'),
        ),
        migrations.AddIndex(
            model_name='subroutinecalltree',
            index=models.Index(fields=['parent_subroutine'], name='subroutine__parent__e40edc_idx'),
        ),
        migrations.AddIndex(
            model_name='subroutinecalltree',
            index=models.Index(fields=['parent_subroutine', 'lineno'], name='subroutine__parent__6a2f16_idx'),
        ),
        migrations.AddConstraint(
            model_name='subroutinecalltree',
            constraint=models.UniqueConstraint(fields=('parent_subroutine', 'child_subroutine', 'lineno'), name='unique_calltree'),
        ),
        migrations.AddConstraint(
            model_name='subroutineargs',
            constraint=models.UniqueConstraint(fields=('subroutine', 'arg_name'), name='unique_sub_args'),
        ),
        migrations.AddIndex(
            model_name='ifevaluationbyhash',
            index=models.Index(fields=['config_hash', 'subroutine', 'is_active', 'start_ln', 'end_ln'], name='if_eval_by__config__0ee32e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ifevaluationbyhash',
            constraint=models.UniqueConstraint(fields=('config_hash', 'flatif'), name='uniq_if_eval_hash_flatif'),
        ),
        migrations.AddConstraint(
            model_name='flatif',
            constraint=models.UniqueConstraint(fields=('start_ln', 'subroutine', 'end_ln'), name='unique_ifs'),
        ),
        migrations.AddIndex(
            model_name='callsitepropagatedeffectbyhash',
            index=models.Index(fields=['var_name', 'status'], name='callsite_pr_var_nam_cdff4d_idx'),
        ),
        migrations.AddIndex(
            model_name='callsitepropagatedeffectbyhash',
            index=models.Index(fields=['var_name', 'member_path_str'], name='callsite_pr_var_nam_672711_idx'),
        ),
        migrations.AddIndex(
            model_name='callsitepropagatedeffectbyhash',
            index=models.Index(fields=['call', 'child_subroutine', 'child_ln'], name='callsite_pr_call_id_c9596d_idx'),
        ),
        migrations.AddIndex(
            model_name='callsitebinding',
            index=models.Index(fields=['call'], name='callsite_bi_call_id_38ca68_idx'),
        ),
        migrations.AddIndex(
            model_name='callsitebinding',
            index=models.Index(fields=['dummy_arg'], name='callsite_bi_dummy_a_2b9ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='callsitebinding',
            index=models.Index(fields=['parent_subroutine', 'var_name'], name='callsite_bi_parent__5e715c_idx'),
        ),
        migrations.AddConstraint(
            model_name='callsitebinding',
            constraint=models.UniqueConstraint(fields=('call', 'dummy_arg', 'var_name', 'member_path_str'), name='uniq_binding_per_arg'),
        ),
        migrations.AddIndex(
            model_name='argsummarybyhash',
            index=models.Index(fields=['subroutine', 'arg', 'ln'], name='arg_access__subrout_a47e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='argsummarybyhash',
            index=models.Index(fields=['subroutine', 'arg', 'status'], name='arg_access__subrout_99b429_idx'),
        ),
        migrations.AddConstraint(
            model_name='argsummarybyhash',
            constraint=models.UniqueConstraint(fields=('subroutine', 'arg', 'ln', 'status', 'member_path'), name='unique_arg_use_by_hash_row'),
        ),
        migrations.AddIndex(
            model_name='argaccess',
            index=models.Index(fields=['subroutine', 'arg', 'ln'], name='arg_access_subrout_c804c0_idx'),
        ),
        migrations.AddIndex(
            model_name='argaccess',
            index=models.Index(fields=['subroutine', 'arg', 'status'], name='arg_access_subrout_abf5d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='argaccess',
            constraint=models.UniqueConstraint(fields=('subroutine', 'arg', 'ln', 'status', 'member_path'), name='unique_arg_use_row'),
        ),
        migrations.AddConstraint(
            model_name='subroutineactiveglobalvars',
            constraint=models.UniqueConstraint(fields=('subroutine', 'instance', 'member', 'status', 'ln'), name='unique_sub_dtype'),
        ),
        migrations.AddConstraint(
            model_name='usertypes',
            constraint=models.UniqueConstraint(fields=('module', 'user_type_name'), name='unique_types'),
        ),
        migrations.AddConstraint(
            model_name='usertypeinstances',
            constraint=models.UniqueConstraint(fields=('inst_module', 'instance_type', 'instance_name'), name='unique_instances'),
        ),
        migrations.AlterUniqueTogether(
            name='typedefinitions',
            unique_together={('user_type', 'member_type', 'member_name', 'type_module')},
        ),
    ]
