# Generated by Django 5.2.8 on 2026-01-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propagatedeffectbyln',
            name='unique_prop',
        ),
        migrations.AddConstraint(
            model_name='propagatedeffectbyln',
            constraint=models.UniqueConstraint(fields=('call_site', 'binding', 'var_name', 'member_path', 'lineno', 'status', 'scope'), name='unique_prop'),
        ),
    ]
