module duplicateMod
contains
subroutine duplicate_weights(unique_sites,total_gridcells)
  use elm_varsur, only : wt_lunit, urban_valid
  implicit none
  integer, intent(in) :: unique_sites
  integer, intent(in) :: total_gridcells
  integer :: g, dim3, l, gcopy
  dim3 = size(wt_lunit,3)
  print *, 'dim3 = ',dim3
  do g = unique_sites+1, total_gridcells
    gcopy = mod(g-1,unique_sites)+1
    do l=1,dim3
      wt_lunit(g,1,l) = wt_lunit(gcopy,1,l)
    end do
    urban_valid(g,1) = urban_valid(gcopy,1)
  end do
end subroutine duplicate_weights
subroutine duplicate_clumps(mode,unique_sites,num_sites)
  use photosynthesismod, only : params_inst
  use landunittype, only : lun_pp
  use sharedparamsmod, only : paramsshareinst
  use vegetationpropertiestype, only : veg_vp
  use elm_instmod, only : canopystate_vars
  use elm_instmod, only : cnstate_vars
  use elm_instmod, only : energyflux_vars
  use elm_instmod, only : frictionvel_vars
  use elm_instmod, only : soilstate_vars
  use elm_instmod, only : solarabs_vars
  use elm_instmod, only : surfalb_vars
  use elm_instmod, only : ch4_vars
  use elm_instmod, only : photosyns_vars
  use gridcelltype, only : grc_pp
  use topounitdatatype, only : top_as
  use topounitdatatype, only : top_af
  use columntype, only : col_pp
  use columndatatype, only : col_es
  use columndatatype, only : col_ws
  use columndatatype, only : col_ef
  use vegetationtype, only : veg_pp
  use vegetationdatatype, only : veg_es
  use vegetationdatatype, only : veg_ws
  use vegetationdatatype, only : veg_ns
  use vegetationdatatype, only : veg_ps
  use vegetationdatatype, only : veg_ef
  use vegetationdatatype, only : veg_wf
  use topounittype, only : top_pp
  use filtermod, only : filter
  use filtermod, only : filter_inactive_and_active
  use decompMod, only : bounds_type, get_clump_bounds, procinfo
  use elm_varcon
  use elm_varpar
  use elm_varctl
  use landunit_varcon
  implicit none
  integer, intent(in) :: mode, unique_sites, num_sites
  type(bounds_type)  :: bounds_copy, bounds
  integer :: errcode, nc,nc_copy, nclumps
  integer :: begp_copy, endp_copy, begp, endp
  integer :: begc_copy, endc_copy, begc, endc
  integer :: begg_copy, endg_copy, begg, endg
  integer :: begt_copy, endt_copy, begt, endt
  integer :: begl_copy, endl_copy, begl, endl
  nclumps = num_sites
  if(mode == 0) then
    do nc=unique_sites+1, num_sites
      nc_copy = mod(nc-1,unique_sites)+1
      call get_clump_bounds(nc,bounds)
      call get_clump_bounds(nc_copy,bounds_copy)
      begg_copy=bounds_copy%begg; endg_copy=bounds_copy%endg
      begt_copy=bounds_copy%begt; endt_copy=bounds_copy%endt
      begl_copy=bounds_copy%begl; endl_copy=bounds_copy%endl
      begc_copy=bounds_copy%begc; endc_copy=bounds_copy%endc
      begp_copy=bounds_copy%begp; endp_copy=bounds_copy%endp
      begg=bounds%begg; endg=bounds%endg
      begt=bounds%begt; endt=bounds%endt
      begl=bounds%begl; endl=bounds%endl
      begc=bounds%begc; endc=bounds%endc
      begp=bounds%begp; endp=bounds%endp
      lun_pp%gridcell(begl:endl) &
        = lun_pp%gridcell(begl_copy:endl_copy)
      lun_pp%topounit(begl:endl) &
        = lun_pp%topounit(begl_copy:endl_copy)
      lun_pp%pfti(begl:endl) &
        = lun_pp%pfti(begl_copy:endl_copy)
      lun_pp%pftf(begl:endl) &
        = lun_pp%pftf(begl_copy:endl_copy)
      lun_pp%itype(begl:endl) &
        = lun_pp%itype(begl_copy:endl_copy)
      lun_pp%lakpoi(begl:endl) &
        = lun_pp%lakpoi(begl_copy:endl_copy)
      lun_pp%urbpoi(begl:endl) &
        = lun_pp%urbpoi(begl_copy:endl_copy)
      lun_pp%active(begl:endl) &
        = lun_pp%active(begl_copy:endl_copy)
      grc_pp%londeg(begg:endg) &
        = grc_pp%londeg(begg_copy:endg_copy)
      grc_pp%slope_deg(begg:endg) &
        = grc_pp%slope_deg(begg_copy:endg_copy)
      grc_pp%max_dayl(begg:endg) &
        = grc_pp%max_dayl(begg_copy:endg_copy)
      grc_pp%dayl(begg:endg) &
        = grc_pp%dayl(begg_copy:endg_copy)
      col_pp%gridcell(begc:endc) &
        = col_pp%gridcell(begc_copy:endc_copy)
      col_pp%topounit(begc:endc) &
        = col_pp%topounit(begc_copy:endc_copy)
      col_pp%landunit(begc:endc) &
        = col_pp%landunit(begc_copy:endc_copy)
      col_pp%itype(begc:endc) &
        = col_pp%itype(begc_copy:endc_copy)
      col_pp%active(begc:endc) &
        = col_pp%active(begc_copy:endc_copy)
      col_pp%snl(begc:endc) &
        = col_pp%snl(begc_copy:endc_copy)
      col_pp%dz(begc:endc,:) &
        = col_pp%dz(begc_copy:endc_copy,:)
      col_pp%z(begc:endc,:) &
        = col_pp%z(begc_copy:endc_copy,:)
      col_pp%is_soil(begc:endc) &
        = col_pp%is_soil(begc_copy:endc_copy)
      col_pp%is_crop(begc:endc) &
        = col_pp%is_crop(begc_copy:endc_copy)
      veg_pp%gridcell(begp:endp) &
        = veg_pp%gridcell(begp_copy:endp_copy)
      veg_pp%topounit(begp:endp) &
        = veg_pp%topounit(begp_copy:endp_copy)
      veg_pp%landunit(begp:endp) &
        = veg_pp%landunit(begp_copy:endp_copy)
      veg_pp%column(begp:endp) &
        = veg_pp%column(begp_copy:endp_copy)
      veg_pp%itype(begp:endp) &
        = veg_pp%itype(begp_copy:endp_copy)
      veg_pp%active(begp:endp) &
        = veg_pp%active(begp_copy:endp_copy)
      veg_pp%is_on_soil_col(begp:endp) &
        = veg_pp%is_on_soil_col(begp_copy:endp_copy)
      veg_pp%is_on_crop_col(begp:endp) &
        = veg_pp%is_on_crop_col(begp_copy:endp_copy)
      veg_pp%is_fates(begp:endp) &
        = veg_pp%is_fates(begp_copy:endp_copy)
      top_pp%topo_grc_ind(begt:endt) &
        = top_pp%topo_grc_ind(begt_copy:endt_copy)
      top_pp%active(begt:endt) &
        = top_pp%active(begt_copy:endt_copy)
    end do
  else
    do nc=unique_sites+1, num_sites
      nc_copy = mod(nc-1,unique_sites)+1
      call get_clump_bounds(nc,bounds)
      call get_clump_bounds(nc_copy,bounds_copy)
      begg_copy=bounds_copy%begg; endg_copy=bounds_copy%endg
      begt_copy=bounds_copy%begt; endt_copy=bounds_copy%endt
      begl_copy=bounds_copy%begl; endl_copy=bounds_copy%endl
      begc_copy=bounds_copy%begc; endc_copy=bounds_copy%endc
      begp_copy=bounds_copy%begp; endp_copy=bounds_copy%endp
      begg=bounds%begg; endg=bounds%endg
      begt=bounds%begt; endt=bounds%endt
      begl=bounds%begl; endl=bounds%endl
      begc=bounds%begc; endc=bounds%endc
      begp=bounds%begp; endp=bounds%endp
      params_inst%kmax(:,:) &
        = params_inst%kmax(:,:)
      canopystate_vars%frac_veg_nosno_patch(begp:endp) &
        = canopystate_vars%frac_veg_nosno_patch(begp_copy:endp_copy)
      canopystate_vars%tlai_patch(begp:endp) &
        = canopystate_vars%tlai_patch(begp_copy:endp_copy)
      canopystate_vars%tsai_patch(begp:endp) &
        = canopystate_vars%tsai_patch(begp_copy:endp_copy)
      canopystate_vars%elai_patch(begp:endp) &
        = canopystate_vars%elai_patch(begp_copy:endp_copy)
      canopystate_vars%esai_patch(begp:endp) &
        = canopystate_vars%esai_patch(begp_copy:endp_copy)
      canopystate_vars%laisun_patch(begp:endp) &
        = canopystate_vars%laisun_patch(begp_copy:endp_copy)
      canopystate_vars%laisha_patch(begp:endp) &
        = canopystate_vars%laisha_patch(begp_copy:endp_copy)
      canopystate_vars%laisun_z_patch(begp:endp,:) &
        = canopystate_vars%laisun_z_patch(begp_copy:endp_copy,:)
      canopystate_vars%laisha_z_patch(begp:endp,:) &
        = canopystate_vars%laisha_z_patch(begp_copy:endp_copy,:)
      canopystate_vars%htop_patch(begp:endp) &
        = canopystate_vars%htop_patch(begp_copy:endp_copy)
      canopystate_vars%displa_patch(begp:endp) &
        = canopystate_vars%displa_patch(begp_copy:endp_copy)
      canopystate_vars%altmax_indx_col(begc:endc) &
        = canopystate_vars%altmax_indx_col(begc_copy:endc_copy)
      canopystate_vars%altmax_lastyear_indx_col(begc:endc) &
        = canopystate_vars%altmax_lastyear_indx_col(begc_copy:endc_copy)
      canopystate_vars%dleaf_patch(begp:endp) &
        = canopystate_vars%dleaf_patch(begp_copy:endp_copy)
      canopystate_vars%lbl_rsc_h2o_patch(begp:endp) &
        = canopystate_vars%lbl_rsc_h2o_patch(begp_copy:endp_copy)
      canopystate_vars%vegwp_patch(begp:endp,:) &
        = canopystate_vars%vegwp_patch(begp_copy:endp_copy,:)
      cnstate_vars%downreg_patch(begp:endp) &
        = cnstate_vars%downreg_patch(begp_copy:endp_copy)
      cnstate_vars%rc14_atm_patch(begp:endp) &
        = cnstate_vars%rc14_atm_patch(begp_copy:endp_copy)
      energyflux_vars%canopy_cond_patch(begp:endp) &
        = energyflux_vars%canopy_cond_patch(begp_copy:endp_copy)
      energyflux_vars%btran_patch(begp:endp) &
        = energyflux_vars%btran_patch(begp_copy:endp_copy)
      energyflux_vars%bsun_patch(begp:endp) &
        = energyflux_vars%bsun_patch(begp_copy:endp_copy)
      energyflux_vars%bsha_patch(begp:endp) &
        = energyflux_vars%bsha_patch(begp_copy:endp_copy)
      energyflux_vars%btran2_patch(begp:endp) &
        = energyflux_vars%btran2_patch(begp_copy:endp_copy)
      energyflux_vars%rresis_patch(begp:endp,:) &
        = energyflux_vars%rresis_patch(begp_copy:endp_copy,:)
      frictionvel_vars%forc_hgt_u_patch(begp:endp) &
        = frictionvel_vars%forc_hgt_u_patch(begp_copy:endp_copy)
      frictionvel_vars%forc_hgt_t_patch(begp:endp) &
        = frictionvel_vars%forc_hgt_t_patch(begp_copy:endp_copy)
      frictionvel_vars%forc_hgt_q_patch(begp:endp) &
        = frictionvel_vars%forc_hgt_q_patch(begp_copy:endp_copy)
      frictionvel_vars%u10_patch(begp:endp) &
        = frictionvel_vars%u10_patch(begp_copy:endp_copy)
      frictionvel_vars%u10_elm_patch(begp:endp) &
        = frictionvel_vars%u10_elm_patch(begp_copy:endp_copy)
      frictionvel_vars%u10_with_gusts_elm_patch(begp:endp) &
        = frictionvel_vars%u10_with_gusts_elm_patch(begp_copy:endp_copy)
      frictionvel_vars%va_patch(begp:endp) &
        = frictionvel_vars%va_patch(begp_copy:endp_copy)
      frictionvel_vars%vds_patch(begp:endp) &
        = frictionvel_vars%vds_patch(begp_copy:endp_copy)
      frictionvel_vars%fv_patch(begp:endp) &
        = frictionvel_vars%fv_patch(begp_copy:endp_copy)
      frictionvel_vars%rb1_patch(begp:endp) &
        = frictionvel_vars%rb1_patch(begp_copy:endp_copy)
      frictionvel_vars%ram1_patch(begp:endp) &
        = frictionvel_vars%ram1_patch(begp_copy:endp_copy)
      frictionvel_vars%z0mv_patch(begp:endp) &
        = frictionvel_vars%z0mv_patch(begp_copy:endp_copy)
      frictionvel_vars%z0hv_patch(begp:endp) &
        = frictionvel_vars%z0hv_patch(begp_copy:endp_copy)
      frictionvel_vars%z0qv_patch(begp:endp) &
        = frictionvel_vars%z0qv_patch(begp_copy:endp_copy)
      frictionvel_vars%z0mg_col(begc:endc) &
        = frictionvel_vars%z0mg_col(begc_copy:endc_copy)
      frictionvel_vars%num_iter_patch(begp:endp) &
        = frictionvel_vars%num_iter_patch(begp_copy:endp_copy)
      frictionvel_vars%rah_above_patch(begp:endp) &
        = frictionvel_vars%rah_above_patch(begp_copy:endp_copy)
      frictionvel_vars%raw_below_patch(begp:endp) &
        = frictionvel_vars%raw_below_patch(begp_copy:endp_copy)
      frictionvel_vars%ustar_patch(begp:endp) &
        = frictionvel_vars%ustar_patch(begp_copy:endp_copy)
      frictionvel_vars%um_patch(begp:endp) &
        = frictionvel_vars%um_patch(begp_copy:endp_copy)
      frictionvel_vars%uaf_patch(begp:endp) &
        = frictionvel_vars%uaf_patch(begp_copy:endp_copy)
      frictionvel_vars%taf_patch(begp:endp) &
        = frictionvel_vars%taf_patch(begp_copy:endp_copy)
      frictionvel_vars%qaf_patch(begp:endp) &
        = frictionvel_vars%qaf_patch(begp_copy:endp_copy)
      frictionvel_vars%obu_patch(begp:endp) &
        = frictionvel_vars%obu_patch(begp_copy:endp_copy)
      frictionvel_vars%zeta_patch(begp:endp) &
        = frictionvel_vars%zeta_patch(begp_copy:endp_copy)
      frictionvel_vars%vpd_patch(begp:endp) &
        = frictionvel_vars%vpd_patch(begp_copy:endp_copy)
      soilstate_vars%hksat_col(begc:endc,:) &
        = soilstate_vars%hksat_col(begc_copy:endc_copy,:)
      soilstate_vars%hk_l_col(begc:endc,:) &
        = soilstate_vars%hk_l_col(begc_copy:endc_copy,:)
      soilstate_vars%smp_l_col(begc:endc,:) &
        = soilstate_vars%smp_l_col(begc_copy:endc_copy,:)
      soilstate_vars%bsw_col(begc:endc,:) &
        = soilstate_vars%bsw_col(begc_copy:endc_copy,:)
      soilstate_vars%watsat_col(begc:endc,:) &
        = soilstate_vars%watsat_col(begc_copy:endc_copy,:)
      soilstate_vars%sucsat_col(begc:endc,:) &
        = soilstate_vars%sucsat_col(begc_copy:endc_copy,:)
      soilstate_vars%soilbeta_col(begc:endc) &
        = soilstate_vars%soilbeta_col(begc_copy:endc_copy)
      soilstate_vars%eff_porosity_col(begc:endc,:) &
        = soilstate_vars%eff_porosity_col(begc_copy:endc_copy,:)
      soilstate_vars%rootr_patch(begp:endp,:) &
        = soilstate_vars%rootr_patch(begp_copy:endp_copy,:)
      soilstate_vars%rootfr_patch(begp:endp,:) &
        = soilstate_vars%rootfr_patch(begp_copy:endp_copy,:)
      soilstate_vars%k_soil_root_patch(begp:endp,:) &
        = soilstate_vars%k_soil_root_patch(begp_copy:endp_copy,:)
      soilstate_vars%root_conductance_patch(begp:endp,:) &
        = soilstate_vars%root_conductance_patch(begp_copy:endp_copy,:)
      soilstate_vars%soil_conductance_patch(begp:endp,:) &
        = soilstate_vars%soil_conductance_patch(begp_copy:endp_copy,:)
      solarabs_vars%parsun_z_patch(begp:endp,:) &
        = solarabs_vars%parsun_z_patch(begp_copy:endp_copy,:)
      solarabs_vars%parsha_z_patch(begp:endp,:) &
        = solarabs_vars%parsha_z_patch(begp_copy:endp_copy,:)
      solarabs_vars%sabv_patch(begp:endp) &
        = solarabs_vars%sabv_patch(begp_copy:endp_copy)
      surfalb_vars%tlai_z_patch(begp:endp,:) &
        = surfalb_vars%tlai_z_patch(begp_copy:endp_copy,:)
      surfalb_vars%nrad_patch(begp:endp) &
        = surfalb_vars%nrad_patch(begp_copy:endp_copy)
      surfalb_vars%vcmaxcintsun_patch(begp:endp) &
        = surfalb_vars%vcmaxcintsun_patch(begp_copy:endp_copy)
      surfalb_vars%vcmaxcintsha_patch(begp:endp) &
        = surfalb_vars%vcmaxcintsha_patch(begp_copy:endp_copy)
      ch4_vars%grnd_ch4_cond_patch(begp:endp) &
        = ch4_vars%grnd_ch4_cond_patch(begp_copy:endp_copy)
      photosyns_vars%c3flag_patch(begp:endp) &
        = photosyns_vars%c3flag_patch(begp_copy:endp_copy)
      photosyns_vars%ac_patch(begp:endp,:) &
        = photosyns_vars%ac_patch(begp_copy:endp_copy,:)
      photosyns_vars%aj_patch(begp:endp,:) &
        = photosyns_vars%aj_patch(begp_copy:endp_copy,:)
      photosyns_vars%ap_patch(begp:endp,:) &
        = photosyns_vars%ap_patch(begp_copy:endp_copy,:)
      photosyns_vars%ag_patch(begp:endp,:) &
        = photosyns_vars%ag_patch(begp_copy:endp_copy,:)
      photosyns_vars%an_patch(begp:endp,:) &
        = photosyns_vars%an_patch(begp_copy:endp_copy,:)
      photosyns_vars%vcmax_z_patch(begp:endp,:) &
        = photosyns_vars%vcmax_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%vcmax25_top_patch(begp:endp) &
        = photosyns_vars%vcmax25_top_patch(begp_copy:endp_copy)
      photosyns_vars%cp_patch(begp:endp) &
        = photosyns_vars%cp_patch(begp_copy:endp_copy)
      photosyns_vars%kc_patch(begp:endp) &
        = photosyns_vars%kc_patch(begp_copy:endp_copy)
      photosyns_vars%ko_patch(begp:endp) &
        = photosyns_vars%ko_patch(begp_copy:endp_copy)
      photosyns_vars%qe_patch(begp:endp) &
        = photosyns_vars%qe_patch(begp_copy:endp_copy)
      photosyns_vars%tpu_z_patch(begp:endp,:) &
        = photosyns_vars%tpu_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%kp_z_patch(begp:endp,:) &
        = photosyns_vars%kp_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%theta_cj_patch(begp:endp) &
        = photosyns_vars%theta_cj_patch(begp_copy:endp_copy)
      photosyns_vars%bbb_patch(begp:endp) &
        = photosyns_vars%bbb_patch(begp_copy:endp_copy)
      photosyns_vars%mbb_patch(begp:endp) &
        = photosyns_vars%mbb_patch(begp_copy:endp_copy)
      photosyns_vars%gs_mol_patch(begp:endp,:) &
        = photosyns_vars%gs_mol_patch(begp_copy:endp_copy,:)
      photosyns_vars%gb_mol_patch(begp:endp) &
        = photosyns_vars%gb_mol_patch(begp_copy:endp_copy)
      photosyns_vars%rh_leaf_patch(begp:endp) &
        = photosyns_vars%rh_leaf_patch(begp_copy:endp_copy)
      photosyns_vars%alphapsnsun_patch(begp:endp) &
        = photosyns_vars%alphapsnsun_patch(begp_copy:endp_copy)
      photosyns_vars%alphapsnsha_patch(begp:endp) &
        = photosyns_vars%alphapsnsha_patch(begp_copy:endp_copy)
      photosyns_vars%rc13_canair_patch(begp:endp) &
        = photosyns_vars%rc13_canair_patch(begp_copy:endp_copy)
      photosyns_vars%rc13_psnsun_patch(begp:endp) &
        = photosyns_vars%rc13_psnsun_patch(begp_copy:endp_copy)
      photosyns_vars%rc13_psnsha_patch(begp:endp) &
        = photosyns_vars%rc13_psnsha_patch(begp_copy:endp_copy)
      photosyns_vars%psnsun_patch(begp:endp) &
        = photosyns_vars%psnsun_patch(begp_copy:endp_copy)
      photosyns_vars%psnsha_patch(begp:endp) &
        = photosyns_vars%psnsha_patch(begp_copy:endp_copy)
      photosyns_vars%c13_psnsun_patch(begp:endp) &
        = photosyns_vars%c13_psnsun_patch(begp_copy:endp_copy)
      photosyns_vars%c13_psnsha_patch(begp:endp) &
        = photosyns_vars%c13_psnsha_patch(begp_copy:endp_copy)
      photosyns_vars%c14_psnsun_patch(begp:endp) &
        = photosyns_vars%c14_psnsun_patch(begp_copy:endp_copy)
      photosyns_vars%c14_psnsha_patch(begp:endp) &
        = photosyns_vars%c14_psnsha_patch(begp_copy:endp_copy)
      photosyns_vars%psnsun_z_patch(begp:endp,:) &
        = photosyns_vars%psnsun_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%psnsha_z_patch(begp:endp,:) &
        = photosyns_vars%psnsha_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%psnsun_wc_patch(begp:endp) &
        = photosyns_vars%psnsun_wc_patch(begp_copy:endp_copy)
      photosyns_vars%psnsha_wc_patch(begp:endp) &
        = photosyns_vars%psnsha_wc_patch(begp_copy:endp_copy)
      photosyns_vars%psnsun_wj_patch(begp:endp) &
        = photosyns_vars%psnsun_wj_patch(begp_copy:endp_copy)
      photosyns_vars%psnsha_wj_patch(begp:endp) &
        = photosyns_vars%psnsha_wj_patch(begp_copy:endp_copy)
      photosyns_vars%psnsun_wp_patch(begp:endp) &
        = photosyns_vars%psnsun_wp_patch(begp_copy:endp_copy)
      photosyns_vars%psnsha_wp_patch(begp:endp) &
        = photosyns_vars%psnsha_wp_patch(begp_copy:endp_copy)
      photosyns_vars%fpsn_patch(begp:endp) &
        = photosyns_vars%fpsn_patch(begp_copy:endp_copy)
      photosyns_vars%fpsn_wc_patch(begp:endp) &
        = photosyns_vars%fpsn_wc_patch(begp_copy:endp_copy)
      photosyns_vars%fpsn_wj_patch(begp:endp) &
        = photosyns_vars%fpsn_wj_patch(begp_copy:endp_copy)
      photosyns_vars%fpsn_wp_patch(begp:endp) &
        = photosyns_vars%fpsn_wp_patch(begp_copy:endp_copy)
      photosyns_vars%lmrsun_patch(begp:endp) &
        = photosyns_vars%lmrsun_patch(begp_copy:endp_copy)
      photosyns_vars%lmrsha_patch(begp:endp) &
        = photosyns_vars%lmrsha_patch(begp_copy:endp_copy)
      photosyns_vars%lmrsun_z_patch(begp:endp,:) &
        = photosyns_vars%lmrsun_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%lmrsha_z_patch(begp:endp,:) &
        = photosyns_vars%lmrsha_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%cisun_z_patch(begp:endp,:) &
        = photosyns_vars%cisun_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%cisha_z_patch(begp:endp,:) &
        = photosyns_vars%cisha_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%rssun_z_patch(begp:endp,:) &
        = photosyns_vars%rssun_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%rssha_z_patch(begp:endp,:) &
        = photosyns_vars%rssha_z_patch(begp_copy:endp_copy,:)
      photosyns_vars%rssun_patch(begp:endp) &
        = photosyns_vars%rssun_patch(begp_copy:endp_copy)
      photosyns_vars%rssha_patch(begp:endp) &
        = photosyns_vars%rssha_patch(begp_copy:endp_copy)
      photosyns_vars%ac_phs_patch(begp:endp,:,:) &
        = photosyns_vars%ac_phs_patch(begp_copy:endp_copy,:,:)
      photosyns_vars%aj_phs_patch(begp:endp,:,:) &
        = photosyns_vars%aj_phs_patch(begp_copy:endp_copy,:,:)
      photosyns_vars%ap_phs_patch(begp:endp,:,:) &
        = photosyns_vars%ap_phs_patch(begp_copy:endp_copy,:,:)
      photosyns_vars%ag_phs_patch(begp:endp,:,:) &
        = photosyns_vars%ag_phs_patch(begp_copy:endp_copy,:,:)
      photosyns_vars%an_sun_patch(begp:endp,:) &
        = photosyns_vars%an_sun_patch(begp_copy:endp_copy,:)
      photosyns_vars%an_sha_patch(begp:endp,:) &
        = photosyns_vars%an_sha_patch(begp_copy:endp_copy,:)
      photosyns_vars%vcmax_z_phs_patch(begp:endp,:,:) &
        = photosyns_vars%vcmax_z_phs_patch(begp_copy:endp_copy,:,:)
      photosyns_vars%kp_z_phs_patch(begp:endp,:,:) &
        = photosyns_vars%kp_z_phs_patch(begp_copy:endp_copy,:,:)
      photosyns_vars%tpu_z_phs_patch(begp:endp,:,:) &
        = photosyns_vars%tpu_z_phs_patch(begp_copy:endp_copy,:,:)
      photosyns_vars%gs_mol_sun_patch(begp:endp,:) &
        = photosyns_vars%gs_mol_sun_patch(begp_copy:endp_copy,:)
      photosyns_vars%gs_mol_sha_patch(begp:endp,:) &
        = photosyns_vars%gs_mol_sha_patch(begp_copy:endp_copy,:)
      top_as%tbot(begt:endt) &
        = top_as%tbot(begt_copy:endt_copy)
      top_as%thbot(begt:endt) &
        = top_as%thbot(begt_copy:endt_copy)
      top_as%pbot(begt:endt) &
        = top_as%pbot(begt_copy:endt_copy)
      top_as%rhobot(begt:endt) &
        = top_as%rhobot(begt_copy:endt_copy)
      top_as%qbot(begt:endt) &
        = top_as%qbot(begt_copy:endt_copy)
      top_as%ubot(begt:endt) &
        = top_as%ubot(begt_copy:endt_copy)
      top_as%vbot(begt:endt) &
        = top_as%vbot(begt_copy:endt_copy)
      top_as%wsresp(begt:endt) &
        = top_as%wsresp(begt_copy:endt_copy)
      top_as%tau_est(begt:endt) &
        = top_as%tau_est(begt_copy:endt_copy)
      top_as%ugust(begt:endt) &
        = top_as%ugust(begt_copy:endt_copy)
      top_as%po2bot(begt:endt) &
        = top_as%po2bot(begt_copy:endt_copy)
      top_as%pco2bot(begt:endt) &
        = top_as%pco2bot(begt_copy:endt_copy)
      top_as%pc13o2bot(begt:endt) &
        = top_as%pc13o2bot(begt_copy:endt_copy)
      top_af%lwrad(begt:endt) &
        = top_af%lwrad(begt_copy:endt_copy)
      col_es%t_soisno(begc:endc,:) &
        = col_es%t_soisno(begc_copy:endc_copy,:)
      col_es%t_h2osfc(begc:endc) &
        = col_es%t_h2osfc(begc_copy:endc_copy)
      col_es%t_grnd(begc:endc) &
        = col_es%t_grnd(begc_copy:endc_copy)
      col_es%thv(begc:endc) &
        = col_es%thv(begc_copy:endc_copy)
      col_es%emg(begc:endc) &
        = col_es%emg(begc_copy:endc_copy)
      col_ws%h2osoi_liq(begc:endc,:) &
        = col_ws%h2osoi_liq(begc_copy:endc_copy,:)
      col_ws%h2osoi_ice(begc:endc,:) &
        = col_ws%h2osoi_ice(begc_copy:endc_copy,:)
      col_ws%h2osoi_vol(begc:endc,:) &
        = col_ws%h2osoi_vol(begc_copy:endc_copy,:)
      col_ws%h2osoi_liqvol(begc:endc,:) &
        = col_ws%h2osoi_liqvol(begc_copy:endc_copy,:)
      col_ws%qg_snow(begc:endc) &
        = col_ws%qg_snow(begc_copy:endc_copy)
      col_ws%qg_soil(begc:endc) &
        = col_ws%qg_soil(begc_copy:endc_copy)
      col_ws%qg_h2osfc(begc:endc) &
        = col_ws%qg_h2osfc(begc_copy:endc_copy)
      col_ws%qg(begc:endc) &
        = col_ws%qg(begc_copy:endc_copy)
      col_ws%dqgdt(begc:endc) &
        = col_ws%dqgdt(begc_copy:endc_copy)
      col_ws%snow_depth(begc:endc) &
        = col_ws%snow_depth(begc_copy:endc_copy)
      col_ws%frac_sno_eff(begc:endc) &
        = col_ws%frac_sno_eff(begc_copy:endc_copy)
      col_ws%frac_h2osfc(begc:endc) &
        = col_ws%frac_h2osfc(begc_copy:endc_copy)
      col_ef%htvp(begc:endc) &
        = col_ef%htvp(begc_copy:endc_copy)
      veg_es%t_veg(begp:endp) &
        = veg_es%t_veg(begp_copy:endp_copy)
      veg_es%t_ref2m(begp:endp) &
        = veg_es%t_ref2m(begp_copy:endp_copy)
      veg_es%t_ref2m_r(begp:endp) &
        = veg_es%t_ref2m_r(begp_copy:endp_copy)
      veg_es%t_a10(begp:endp) &
        = veg_es%t_a10(begp_copy:endp_copy)
      veg_es%thm(begp:endp) &
        = veg_es%thm(begp_copy:endp_copy)
      veg_es%emv(begp:endp) &
        = veg_es%emv(begp_copy:endp_copy)
      veg_ws%h2ocan(begp:endp) &
        = veg_ws%h2ocan(begp_copy:endp_copy)
      veg_ws%q_ref2m(begp:endp) &
        = veg_ws%q_ref2m(begp_copy:endp_copy)
      veg_ws%rh_ref2m(begp:endp) &
        = veg_ws%rh_ref2m(begp_copy:endp_copy)
      veg_ws%rh_ref2m_r(begp:endp) &
        = veg_ws%rh_ref2m_r(begp_copy:endp_copy)
      veg_ws%rh_af(begp:endp) &
        = veg_ws%rh_af(begp_copy:endp_copy)
      veg_ws%fwet(begp:endp) &
        = veg_ws%fwet(begp_copy:endp_copy)
      veg_ws%fdry(begp:endp) &
        = veg_ws%fdry(begp_copy:endp_copy)
      veg_ns%leafn(begp:endp) &
        = veg_ns%leafn(begp_copy:endp_copy)
      veg_ps%leafp(begp:endp) &
        = veg_ps%leafp(begp_copy:endp_copy)
      veg_ef%eflx_sh_grnd(begp:endp) &
        = veg_ef%eflx_sh_grnd(begp_copy:endp_copy)
      veg_ef%eflx_sh_veg(begp:endp) &
        = veg_ef%eflx_sh_veg(begp_copy:endp_copy)
      veg_ef%eflx_sh_snow(begp:endp) &
        = veg_ef%eflx_sh_snow(begp_copy:endp_copy)
      veg_ef%eflx_sh_soil(begp:endp) &
        = veg_ef%eflx_sh_soil(begp_copy:endp_copy)
      veg_ef%eflx_sh_h2osfc(begp:endp) &
        = veg_ef%eflx_sh_h2osfc(begp_copy:endp_copy)
      veg_ef%dlrad(begp:endp) &
        = veg_ef%dlrad(begp_copy:endp_copy)
      veg_ef%ulrad(begp:endp) &
        = veg_ef%ulrad(begp_copy:endp_copy)
      veg_ef%taux(begp:endp) &
        = veg_ef%taux(begp_copy:endp_copy)
      veg_ef%tauy(begp:endp) &
        = veg_ef%tauy(begp_copy:endp_copy)
      veg_ef%cgrnd(begp:endp) &
        = veg_ef%cgrnd(begp_copy:endp_copy)
      veg_ef%cgrndl(begp:endp) &
        = veg_ef%cgrndl(begp_copy:endp_copy)
      veg_ef%cgrnds(begp:endp) &
        = veg_ef%cgrnds(begp_copy:endp_copy)
      veg_wf%qflx_evap_soi(begp:endp) &
        = veg_wf%qflx_evap_soi(begp_copy:endp_copy)
      veg_wf%qflx_evap_veg(begp:endp) &
        = veg_wf%qflx_evap_veg(begp_copy:endp_copy)
      veg_wf%qflx_tran_veg(begp:endp) &
        = veg_wf%qflx_tran_veg(begp_copy:endp_copy)
      veg_wf%qflx_ev_snow(begp:endp) &
        = veg_wf%qflx_ev_snow(begp_copy:endp_copy)
      veg_wf%qflx_ev_soil(begp:endp) &
        = veg_wf%qflx_ev_soil(begp_copy:endp_copy)
      veg_wf%qflx_ev_h2osfc(begp:endp) &
        = veg_wf%qflx_ev_h2osfc(begp_copy:endp_copy)
      veg_wf%irrig_rate(begp:endp) &
        = veg_wf%irrig_rate(begp_copy:endp_copy)
      veg_wf%n_irrig_steps_left(begp:endp) &
        = veg_wf%n_irrig_steps_left(begp_copy:endp_copy)
      filter%pcropp(begp:endp) &
        = filter%pcropp(begp_copy:endp_copy)
      filter%ppercropp(begp:endp) &
        = filter%ppercropp(begp_copy:endp_copy)
      filter%soilnopcropp(begp:endp) &
        = filter%soilnopcropp(begp_copy:endp_copy)
      filter%lakep(begp:endp) &
        = filter%lakep(begp_copy:endp_copy)
      filter%nolakep(begp:endp) &
        = filter%nolakep(begp_copy:endp_copy)
      filter%lakec(begc:endc) &
        = filter%lakec(begc_copy:endc_copy)
      filter%nolakec(begc:endc) &
        = filter%nolakec(begc_copy:endc_copy)
      filter%soilc(begc:endc) &
        = filter%soilc(begc_copy:endc_copy)
      filter%soilp(begp:endp) &
        = filter%soilp(begp_copy:endp_copy)
      filter%hydrologyc(begc:endc) &
        = filter%hydrologyc(begc_copy:endc_copy)
      filter%hydrononsoic(begc:endc) &
        = filter%hydrononsoic(begc_copy:endc_copy)
      filter%urbanl(begl:endl) &
        = filter%urbanl(begl_copy:endl_copy)
      filter%nourbanl(begl:endl) &
        = filter%nourbanl(begl_copy:endl_copy)
      filter%urbanc(begc:endc) &
        = filter%urbanc(begc_copy:endc_copy)
      filter%nourbanc(begc:endc) &
        = filter%nourbanc(begc_copy:endc_copy)
      filter%urbanp(begp:endp) &
        = filter%urbanp(begp_copy:endp_copy)
      filter%nourbanp(begp:endp) &
        = filter%nourbanp(begp_copy:endp_copy)
      filter%nolakeurbanp(begp:endp) &
        = filter%nolakeurbanp(begp_copy:endp_copy)
      filter%icemecc(begc:endc) &
        = filter%icemecc(begc_copy:endc_copy)
      filter%do_smb_c(begc:endc) &
        = filter%do_smb_c(begc_copy:endc_copy)
      filter_inactive_and_active%pcropp(begp:endp) &
        = filter_inactive_and_active%pcropp(begp_copy:endp_copy)
      filter_inactive_and_active%ppercropp(begp:endp) &
        = filter_inactive_and_active%ppercropp(begp_copy:endp_copy)
      filter_inactive_and_active%soilnopcropp(begp:endp) &
        = filter_inactive_and_active%soilnopcropp(begp_copy:endp_copy)
      filter_inactive_and_active%lakep(begp:endp) &
        = filter_inactive_and_active%lakep(begp_copy:endp_copy)
      filter_inactive_and_active%nolakep(begp:endp) &
        = filter_inactive_and_active%nolakep(begp_copy:endp_copy)
      filter_inactive_and_active%lakec(begc:endc) &
        = filter_inactive_and_active%lakec(begc_copy:endc_copy)
      filter_inactive_and_active%nolakec(begc:endc) &
        = filter_inactive_and_active%nolakec(begc_copy:endc_copy)
      filter_inactive_and_active%soilc(begc:endc) &
        = filter_inactive_and_active%soilc(begc_copy:endc_copy)
      filter_inactive_and_active%soilp(begp:endp) &
        = filter_inactive_and_active%soilp(begp_copy:endp_copy)
      filter_inactive_and_active%hydrologyc(begc:endc) &
        = filter_inactive_and_active%hydrologyc(begc_copy:endc_copy)
      filter_inactive_and_active%hydrononsoic(begc:endc) &
        = filter_inactive_and_active%hydrononsoic(begc_copy:endc_copy)
      filter_inactive_and_active%urbanl(begl:endl) &
        = filter_inactive_and_active%urbanl(begl_copy:endl_copy)
      filter_inactive_and_active%nourbanl(begl:endl) &
        = filter_inactive_and_active%nourbanl(begl_copy:endl_copy)
      filter_inactive_and_active%urbanc(begc:endc) &
        = filter_inactive_and_active%urbanc(begc_copy:endc_copy)
      filter_inactive_and_active%nourbanc(begc:endc) &
        = filter_inactive_and_active%nourbanc(begc_copy:endc_copy)
      filter_inactive_and_active%urbanp(begp:endp) &
        = filter_inactive_and_active%urbanp(begp_copy:endp_copy)
      filter_inactive_and_active%nourbanp(begp:endp) &
        = filter_inactive_and_active%nourbanp(begp_copy:endp_copy)
      filter_inactive_and_active%nolakeurbanp(begp:endp) &
        = filter_inactive_and_active%nolakeurbanp(begp_copy:endp_copy)
      filter_inactive_and_active%icemecc(begc:endc) &
        = filter_inactive_and_active%icemecc(begc_copy:endc_copy)
      filter_inactive_and_active%do_smb_c(begc:endc) &
        = filter_inactive_and_active%do_smb_c(begc_copy:endc_copy)
  end do
  end if
end subroutine duplicate_clumps
end module
