# Generated by Django 5.2.8 on 2026-01-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subroutineelmtypesbyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='propagatedeffectbyln',
            name='first_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propagated_member', to='app.typedefinitions'),
        ),
        migrations.AddField(
            model_name='propagatedeffectbyln',
            name='from_arg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propagated_arg', to='app.subroutineargs'),
        ),
        migrations.AddField(
            model_name='propagatedeffectbyln',
            name='from_elmtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propagated_inst', to='app.usertypeinstances'),
        ),
        migrations.AddField(
            model_name='propagatedeffectbyln',
            name='from_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propagated_local', to='app.subroutinelocalarrays'),
        ),
        migrations.AddField(
            model_name='subroutineelmtypesbyconfig',
            name='arg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_args_by_config', to='app.subroutineargs'),
        ),
        migrations.AddField(
            model_name='subroutineelmtypesbyconfig',
            name='member_path',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subroutineelmtypesbyconfig',
            name='var_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subroutineelmtypesbyconfig',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_instances_by_config', to='app.usertypeinstances'),
        ),
        migrations.AlterField(
            model_name='subroutineelmtypesbyconfig',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_members_by_config', to='app.typedefinitions'),
        ),
        migrations.AddConstraint(
            model_name='subroutineelmtypesbyconfig',
            constraint=models.UniqueConstraint(fields=('subroutine', 'var_name', 'member_path', 'status', 'ln', 'config_hash'), name='unique_sub_dtype_by_config'),
        ),
    ]
