# Generated by Django 5.2.8 on 2026-02-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_callsitebinding_uniq_binding_per_arg_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='callsitebinding',
            name='uniq_binding_per_arg',
        ),
        migrations.AddConstraint(
            model_name='callsitebinding',
            constraint=models.UniqueConstraint(fields=('call', 'dummy_arg', 'var_name', 'member_path_str', 'nested_level'), name='uniq_binding_per_arg'),
        ),
    ]
