# Generated by Django 5.2.8 on 2026-02-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_callsitebinding_uniq_binding_per_arg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subroutineelmtypesbyconfig',
            name='indirect',
            field=models.BooleanField(default=False),
        ),
    ]
