# Generated by Django 5.1.2 on 2025-10-05 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatIf",
            fields=[
                ("flatif_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_ln", models.IntegerField()),
                ("end_ln", models.IntegerField()),
                ("condition", models.TextField()),
                ("active", models.BooleanField()),
            ],
            options={
                "db_table": "flat_if_blocks",
            },
        ),
        migrations.CreateModel(
            name="Modules",
            fields=[
                ("module_id", models.AutoField(primary_key=True, serialize=False)),
                ("module_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "modules",
            },
        ),
        migrations.CreateModel(
            name="IntrinsicGlobals",
            fields=[
                ("var_id", models.AutoField(primary_key=True, serialize=False)),
                ("dim", models.IntegerField()),
                ("var_type", models.CharField(max_length=50)),
                ("var_name", models.CharField(max_length=100)),
                ("bounds", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "gv_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_var",
                        to="app.modules",
                    ),
                ),
            ],
            options={
                "db_table": "intrinsic_globals",
            },
        ),
        migrations.CreateModel(
            name="NamelistVariable",
            fields=[
                ("nml_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "active_var_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namelist",
                        to="app.intrinsicglobals",
                    ),
                ),
            ],
            options={
                "db_table": "namelist_variables",
            },
        ),
        migrations.CreateModel(
            name="FlatIfNamelistVar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "flatif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.flatif"
                    ),
                ),
                (
                    "namelist_var",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.namelistvariable",
                    ),
                ),
            ],
            options={
                "db_table": "flat_if_namelist",
            },
        ),
        migrations.CreateModel(
            name="PresetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("data", models.JSONField(default=dict)),
                (
                    "preset_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "preset_configs",
                "indexes": [
                    models.Index(
                        fields=["preset_hash"], name="preset_conf_preset__03b97b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subroutines",
            fields=[
                ("subroutine_id", models.AutoField(primary_key=True, serialize=False)),
                ("subroutine_name", models.CharField(max_length=100)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subroutine_module",
                        to="app.modules",
                    ),
                ),
            ],
            options={
                "db_table": "subroutines",
            },
        ),
        migrations.CreateModel(
            name="SubroutineLocalArrays",
            fields=[
                ("local_arry_id", models.AutoField(primary_key=True, serialize=False)),
                ("array_name", models.CharField(max_length=100)),
                ("dim", models.IntegerField()),
                (
                    "subroutine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subroutine_locals",
                        to="app.subroutines",
                    ),
                ),
            ],
            options={
                "db_table": "subroutine_local_arrays",
            },
        ),
        migrations.CreateModel(
            name="SubroutineIntrinsicGlobals",
            fields=[
                ("sub_gv_id", models.AutoField(primary_key=True, serialize=False)),
                ("gv_ln", models.IntegerField(default=-1)),
                (
                    "gv_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_intrinsic",
                        to="app.intrinsicglobals",
                    ),
                ),
                (
                    "sub_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subroutine_global_vars",
                        to="app.subroutines",
                    ),
                ),
            ],
            options={
                "db_table": "subroutine_intrinsic_globals",
            },
        ),
        migrations.CreateModel(
            name="SubroutineCalltree",
            fields=[
                ("parent_id", models.AutoField(primary_key=True, serialize=False)),
                ("lineno", models.IntegerField()),
                (
                    "child_subroutine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_subroutine",
                        to="app.subroutines",
                    ),
                ),
                (
                    "parent_subroutine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_subroutine",
                        to="app.subroutines",
                    ),
                ),
            ],
            options={
                "db_table": "subroutine_calltree",
            },
        ),
        migrations.CreateModel(
            name="SubroutineArgs",
            fields=[
                ("arg_id", models.AutoField(primary_key=True, serialize=False)),
                ("arg_type", models.CharField(max_length=100)),
                ("arg_name", models.CharField(max_length=100)),
                ("dim", models.IntegerField()),
                (
                    "subroutine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subroutine_args",
                        to="app.subroutines",
                    ),
                ),
            ],
            options={
                "db_table": "subroutine_args",
            },
        ),
        migrations.CreateModel(
            name="IfEvaluationByHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_hash", models.CharField(db_index=True, max_length=64)),
                ("start_ln", models.IntegerField()),
                ("end_ln", models.IntegerField()),
                ("is_active", models.BooleanField()),
                (
                    "flatif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.flatif"
                    ),
                ),
                (
                    "subroutine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.subroutines",
                    ),
                ),
            ],
            options={
                "db_table": "if_eval_by_hash",
            },
        ),
        migrations.AddField(
            model_name="flatif",
            name="subroutine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flat_ifs",
                to="app.subroutines",
            ),
        ),
        migrations.CreateModel(
            name="TypeDefinitions",
            fields=[
                ("define_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_type", models.CharField(max_length=100)),
                ("member_name", models.CharField(max_length=100)),
                ("dim", models.IntegerField()),
                ("bounds", models.CharField(max_length=100)),
                (
                    "type_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_def_module",
                        to="app.modules",
                    ),
                ),
            ],
            options={
                "db_table": "type_definitions",
            },
        ),
        migrations.CreateModel(
            name="UserTypeInstances",
            fields=[
                ("instance_id", models.AutoField(primary_key=True, serialize=False)),
                ("instance_name", models.CharField(max_length=100)),
                (
                    "inst_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_module",
                        to="app.modules",
                    ),
                ),
            ],
            options={
                "db_table": "user_type_instances",
            },
        ),
        migrations.CreateModel(
            name="SubroutineActiveGlobalVars",
            fields=[
                ("variable_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=2)),
                ("ln", models.IntegerField(default=-1)),
                (
                    "subroutine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subroutine_dtype_vars",
                        to="app.subroutines",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_member",
                        to="app.typedefinitions",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_instances",
                        to="app.usertypeinstances",
                    ),
                ),
            ],
            options={
                "db_table": "subroutine_active_global_vars",
            },
        ),
        migrations.CreateModel(
            name="UserTypes",
            fields=[
                ("user_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type_name", models.CharField(max_length=100, unique=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_type_module",
                        to="app.modules",
                    ),
                ),
            ],
            options={
                "db_table": "user_types",
            },
        ),
        migrations.AddField(
            model_name="usertypeinstances",
            name="instance_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instance_type",
                to="app.usertypes",
            ),
        ),
        migrations.AddField(
            model_name="typedefinitions",
            name="user_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_type_def",
                to="app.usertypes",
            ),
        ),
        migrations.CreateModel(
            name="ConfigProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("data", models.JSONField(default=dict)),
                (
                    "user_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "config_profile",
                "indexes": [
                    models.Index(
                        fields=["owner", "user_hash"],
                        name="config_prof_owner_i_bbe804_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"),
                        name="uniq_configprofile_name_per_owner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModuleDependency",
            fields=[
                ("dependency_id", models.AutoField(primary_key=True, serialize=False)),
                ("object_used", models.CharField(max_length=100)),
                (
                    "dep_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moduledependency_dep_module_set",
                        to="app.modules",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.modules"
                    ),
                ),
            ],
            options={
                "db_table": "module_dependency",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module", "dep_module", "object_used"),
                        name="unique_mod_dep",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="intrinsicglobals",
            index=models.Index(
                fields=["gv_module", "var_name"], name="intrinsic_g_gv_modu_4132ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="intrinsicglobals",
            constraint=models.UniqueConstraint(
                fields=("gv_module", "var_name"), name="unique_globals"
            ),
        ),
        migrations.AddConstraint(
            model_name="namelistvariable",
            constraint=models.UniqueConstraint(
                fields=("active_var_id",), name="unique_nml_var"
            ),
        ),
        migrations.AddConstraint(
            model_name="flatifnamelistvar",
            constraint=models.UniqueConstraint(
                fields=("id", "flatif", "namelist_var"), name="unique_flatif_var"
            ),
        ),
        migrations.AddConstraint(
            model_name="subroutines",
            constraint=models.UniqueConstraint(
                fields=("subroutine_name", "module"), name="unique_subs"
            ),
        ),
        migrations.AddConstraint(
            model_name="subroutinelocalarrays",
            constraint=models.UniqueConstraint(
                fields=("subroutine", "array_name"), name="unique_sub_locals"
            ),
        ),
        migrations.AddConstraint(
            model_name="subroutineintrinsicglobals",
            constraint=models.UniqueConstraint(
                fields=("gv_id", "sub_id"), name="unique_sub_intrinsic"
            ),
        ),
        migrations.AddConstraint(
            model_name="subroutinecalltree",
            constraint=models.UniqueConstraint(
                fields=("parent_subroutine", "child_subroutine", "lineno"),
                name="unique_calltree",
            ),
        ),
        migrations.AddConstraint(
            model_name="subroutineargs",
            constraint=models.UniqueConstraint(
                fields=("subroutine", "arg_type", "arg_name", "dim"),
                name="unique_sub_args",
            ),
        ),
        migrations.AddIndex(
            model_name="ifevaluationbyhash",
            index=models.Index(
                fields=["config_hash", "subroutine", "is_active", "start_ln", "end_ln"],
                name="if_eval_by__config__0ee32e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ifevaluationbyhash",
            constraint=models.UniqueConstraint(
                fields=("config_hash", "flatif"), name="uniq_if_eval_hash_flatif"
            ),
        ),
        migrations.AddConstraint(
            model_name="flatif",
            constraint=models.UniqueConstraint(
                fields=("flatif_id", "start_ln", "subroutine", "end_ln"),
                name="unique_ifs",
            ),
        ),
        migrations.AddConstraint(
            model_name="subroutineactiveglobalvars",
            constraint=models.UniqueConstraint(
                fields=("subroutine", "instance", "member", "status", "ln"),
                name="unique_sub_dtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertypes",
            constraint=models.UniqueConstraint(
                fields=("module", "user_type_name"), name="unique_types"
            ),
        ),
        migrations.AddConstraint(
            model_name="usertypeinstances",
            constraint=models.UniqueConstraint(
                fields=("inst_module", "instance_type", "instance_name"),
                name="unique_instances",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="typedefinitions",
            unique_together={
                ("user_type", "member_type", "member_name", "type_module")
            },
        ),
    ]
