# Generated by Django 5.2.8 on 2026-01-31 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_propagatedeffectbyln_first_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subroutineelmtypesbyconfig',
            name='arg',
        ),
        migrations.AddField(
            model_name='callsitebinding',
            name='first_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bound_member', to='app.typedefinitions'),
        ),
        migrations.AddField(
            model_name='callsitebinding',
            name='from_arg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bound_arg', to='app.subroutineargs'),
        ),
        migrations.AddField(
            model_name='callsitebinding',
            name='from_elmtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bound_inst', to='app.usertypeinstances'),
        ),
        migrations.AddField(
            model_name='callsitebinding',
            name='from_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bound_local', to='app.subroutinelocalarrays'),
        ),
    ]
